apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aonec-bot
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    ingress.alb.yc.io/subnets: fl8hudiu88nghctpeh47
    ingress.alb.yc.io/external-ipv4-address: 51.250.41.131
    ingress.alb.yc.io/group-name: ecbot
spec:
  tls:
    - hosts:
        - bot.aonec-bot.ru
      secretName: yc-certmgr-cert-id-fpqinj4jom0rala85m7b
  rules:
    - host: bot.aonec-bot.ru
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: aonec-bot
                port:
                  number: 80