apiVersion: apps/v1
kind: Deployment
metadata:
  name: aonec_bot
spec:
  template:
    spec:
      containers:
        - name: aonec_bot
          image: aonec_bot_image_name
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.1"
            limits:
              memory: "256Mi"
              cpu: "0.25"