apiVersion: v1
kind: Service
metadata:
  labels:
    app: aonec_bot
  name: aonec_bot
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 80
  type: NodePort
  selector:
    app: aonec_bot