apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
- ../../base/
- readings_bot-ingress.yml

patches:
  - path: readings_bot-deployment.yml

images:
  - name: readings-bot_image_name
    newName: cr.yandex/crpnm76utfphmac4qo1t/readings-bot
    newTag: 0.0.3
