name: Deploy aonec_bot prod

on:
  workflow_dispatch:
        
jobs:
  call_deploy_workflow:
    if: |
      !cancelled()
    uses: ./.github/workflows/deploy_aonec.yml
    with:
      deploy_script_name: aonec_bot/prod
    secrets: inherit
