name: _deploy-base

on:
  workflow_call:
    inputs:
      deploy_script_name:
        required: true
        type: string
        
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run commands on Gateway Virtual Machine
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.YCGATEHOST }}
          username: ${{ secrets.YCDEPLOYUSERNAME }}
          key: ${{ secrets.YCDEPLOYUSERSERT }}
          script: |
            cd /home/deploy/deploy_scripts
            ./${{ inputs.deploy_script_name }}
