name: Deploy spa prod

on:
  push:
    branches:
      - main
        
jobs:
  call_deploy_workflow:
    if: |
      !cancelled()
    uses: ./.github/workflows/deploy.yml
    with:
      deploy_script_name: spa/prod
    secrets: inherit
