name: Deploy readings_bot prod

on:
  workflow_dispatch:
        
jobs:
  call_deploy_workflow:
    if: |
      !cancelled()
    uses: ./.github/workflows/deploy.yml
    with:
      deploy_script_name: readings_bot/prod
    secrets: inherit
